# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wukege.github.io/" # the base hostname & protocol for your site 

# User settings
username: wukege
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: wukege
email: gs.jp@163.com
twitter_username: wukege
github_username:  wukege
gplus_username:  wukege
disqus_username: wukege

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: baidu
    url: www.baidu.com

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
